version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/slack-threads}
      - HOST=${HOST:-http://localhost}
      - PORT=${PORT:-3000}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - RANDOM_SECRET=${RANDOM_SECRET}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: